- hosts: appdeploy
  gather_facts: false
  sudo: true
  tasks:
    - name: Deploy App
      copy src=/var/lib/jenkins/jobs/tomcat_test /testapp.war dest="/opt/apache-tomcat-8.5.35/webapps/testapp##{{ buildnum }}.war" owner=tomcat group=tomcat
