- hosts: appdeploy
  gather_facts: false
  sudo: true
  tasks:
    - name: Deploy App
      copy src=/var/lib/jenkins/jobs/workspace/tomcat_test /testapp.war dest="/opt/local/apache-tomat-8.0.23/webapps/testapp##{{ buildnum }}.war" owner=tomcat group=tomcat
